[package]
name = "modify-by"
version = "0.1.0"
edition = "2024"

[dependencies]
# merge = "0.2.0"
serde = { version = "1", optional = true }


[dev-dependencies]
serde_json = { version = "1" }

[features]
serde = ["dep:serde"]
